#!/bin/bash
d=$(date +"%d-%b-%Y")

users="irtiza"

#While loop to read line by line
#while IFS= read -r line; do
printf '%s\n' "$users" | while IFS= read -r line
do
    if getent passwd $line > /dev/null 2>&1; then
        echo "User Already exists"
    else

        useradd -m -d /home/$line -c "Application User, Created on $d" -s /bin/bash $line;
        echo "irtiza@786" | passwd --stdin $line


       echo -e "\nCmnd_Alias APPSCMD = /usr/bin/atop, /usr/bin/cal, /bin/cat, /usr/bin/clear, /bin/cp, /usr/bin/crontab, /bin/date, /bin/df, /bin/echo/usr, /bin/du, /bin/egrep, /bin/find, /usr/bin/free, /usr/bin/ftp, /bin/grep, /usr/bin/head, /bin/hostname, /sbin/ifconfig, /usr/bin/iproxy, /usr/bin/java, /bin/kill, /usr/bin/less, /usr/bin/locate, /bin/ls, /bin/lsblk, /usr/sbin/lsof, /bin/mkdir, /bin/more, /bin/mv, /bin/netstat, /usr/bin/nproc, /usr/bin/nslookup, /usr/bin/passwd, /bin/ping, /bin/ps, /bin/pwd, /usr/bin/python, /bin/rm, /bin/rmdir, /usr/bin/rsync, /usr/bin/scp, /usr/bin/sftp, /bin/sh, /bin/sort, /usr/bin/ssh, /usr/bin/sudo, /bin/tar, /usr/bin/telnet, /usr/bin/top, /bin/touch, /usr/sbin/tcpdump, /usr/bin/unzip, /usr/bin/uptime, /usr/bin/users, /bin/vi, /usr/bin/w, /usr/bin/wc, /usr/bin/wget, /usr/bin/who, /usr/bin/whoami, /bin/zcat, /usr/bin/zgrep, /usr/bin/zip" >> /etc/sudoers;

        echo -e "\nirtiza ALL=(ALL)\t NOPASSWD: APPSCMD " >> /etc/sudoers;
    fi
done
